### ISSUE TITLE
用不起呀

### ISSUE THREAD

**Issue by zkbutt** [coredumplabs/thingsboard-micropython#3]
发两次就卡住吗，而且都没有成功，是怎么回事呢？
![图片](https://user-images.githubusercontent.com/18031838/161728475-4440bc83-4245-4f82-99bd-1bbed852d637.png)

**Comment by zkbutt** [comment]
MicroPython v1.18

**Comment by manuargue** [comment]
Hello. Could you please share your code? It’s hard to know what’s going on without it..

**Comment by manuargue** [comment]
@zkbutt I'm closing this issue since there was no feedback. Please feel free to re-open it and add more details.
